version: "3"
services:
  api:
    build: ./backend
    ports:
      - "8000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/blog/"]
      timeout: 15s
      retries: 3
      start_period: 10s
    restart: unless-stopped
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web:3000/"]
      timeout: 15s
      retries: 3
      start_period: 10s
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      api:
        condition: service_healthy
      web:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
